"""Add state

Revision ID: cb11df18c46a
Revises: b43aa6647c06
Create Date: 2018-07-20 02:56:13.861167

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'cb11df18c46a'
down_revision = 'b43aa6647c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'states',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('telegram_id', sa.BigInteger(), nullable=False),
        sa.Column('state', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_states_state'), 'states', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_states_state'), table_name='states')
    op.drop_table('states')
    # ### end Alembic commands ###
